module.exports = {
  extends: ['eslint:recommended', 'plugin:import/errors'],
  reportUnusedDisableDirectives: true,
  rules: {
    'array-bracket-spacing': ['error', 'never'],
    'arrow-parens': ['error', 'always'],
    'comma-dangle': ['error', 'always-multiline'],
    curly: 'error',
    eqeqeq: ['error', 'allow-null'],
    'import/extensions': [
      'error',
      'always',
      {js: 'never', jsx: 'never', ts: 'never', tsx: 'never'},
    ],
    'import/first': 'error',
    'import/no-anonymous-default-export': 'off',
    'import/no-extraneous-dependencies': 'error',
    'import/order': ['error', {alphabetize: {order: 'asc'}}],
    'no-alert': 'error',
    'no-bitwise': 'error',
    'no-prototype-builtins': 'off',
    'no-unused-vars': ['error', {args: 'none', ignoreRestSiblings: true}],
    'no-var': 'error',
    'object-curly-spacing': ['error', 'never'],
    'prefer-const': 'error',
    'prefer-arrow-callback': 'error',
    quotes: ['error', 'single', {avoidEscape: true}],
    radix: 'error',
  },
};
