name: Tests
on: [push, pull_request]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, macos-10.15, windows-2019]
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Install
        # Ignore scripts such as `prepare`, which normally run on install. We're using `prepare` to
        # build the TypeScript for local development. Here on CI, though, we don't want this to fail
        # on any type errors. Instead, the build step will catch and report those.
        run: yarn install --ignore-scripts
      - name: Build
        run: yarn build
      - name: Ensure project references are up to date
        run: yarn check-ts-references
        # check-ts-references does not seem to be able to run on Windows.
        if: matrix.os != 'windows-2019'
      - name: Lint
        run: yarn lint
      - name: Unit tests
        run: yarn test:only
