name: Tests
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs ⛔
        uses: styfle/cancel-workflow-action@0.11.0
      - name: Checkout
        uses: actions/checkout@master
      - name: Setup Node 😻
        uses: actions/setup-node@v3
        with:
          node-version-file: '.node-version'
          cache: 'yarn'
      - name: Install
        run: yarn install --immutable
      - name: Build
        run: yarn build
      - name: Ensure project references are up to date
        run: yarn check-ts-references
      - name: Lint
        run: yarn lint
      - name: Unit tests
        run: yarn test:only
