name: Tests
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Install
        run: yarn install
      - name: Build
        run: yarn build
      - name: Ensure project references are up to date
        run: yarn check-ts-references
      - name: Lint
        run: yarn lint
      - name: Unit tests
        run: yarn test:only
